version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-20.04
    container_name: mssql
    environment:
      SA_PASSWORD: "P@ssw0rd123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - sql_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - sql_network
    depends_on:
      - mssql

  initdb:
    image: mcr.microsoft.com/mssql-tools
    container_name: initdb
    depends_on:
      - mssql
    volumes:
      - ./init.sql:/init.sql
    entrypoint: /bin/bash
    command: >
      -c "
      sleep 20;
      /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P P@ssw0rd123! -i /init.sql
      "
    networks:
      - sql_network

volumes:
  mssql_data:

networks:
  sql_network:
    driver: bridge