version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-20.04
    container_name: mssql
    environment:
      SA_PASSWORD: "P@ssw0rd123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "P@ssw0rd123!", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10
      start_period: 20s

  initdb:
    image: mcr.microsoft.com/mssql-tools
    container_name: initdb
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./init.sql:/init.sql
    entrypoint: >
      sh -c "
        echo 'Waiting for SQL Server to accept connections...';
        sleep 10;
        echo 'Converting SQL file to UTF-16LE for Unicode support...';
        iconv -f utf-8 -t utf-16le /init.sql > /converted.sql;
        echo 'Running init.sql via sqlcmd...';
        /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P P@ssw0rd123! -i /converted.sql;
        echo 'Database initialized with Polish data'"

volumes:
  mssqldata: